### ISSUE TITLE
What it for?

### ISSUE THREAD

**Issue by shabanovd** [JakubDziworski/Enkel-JVM-language#4]
Hey, is it playground or there are needs/wants hidden somewhere? (just wander)

**Comment by JakubDziworski** [comment]
100% playground. Writing language is fun, and it made me understand jvm way better. Also, I could find only few guides (and none of them was even complete) on how to get started with your own jvm language. It was a motiviation to blog about my progress with Enkel.

**Comment by shabanovd** [comment]
I see. Do you interesting to write jvm itself? There is [Phantom OS](https://github.com/dzavalishin/phantomuserland), and I wish to code jvm for it, but I need partner for it. The goal is same as you have here - understand jvm better.

**Comment by JakubDziworski** [comment]
We can chat via hangout or email. Please contact me at jakub.dziworski@gmail.com.
