### ISSUE TITLE
Fields thru objects not working correctly

### ISSUE THREAD

**Issue by Altaflux** [JakubDziworski/Enkel-JVM-language#6]
The language is bound into only being able to call objects of fields that belong to the same class being worked.
This caused by the way objects reference when called are forced to call "this" always and have no ownership.
Also there is no concrete exposure of "this" which causes trouble when working with local variables or fields.

I have a fork of Enkel which fixes all of this issues and allows to gracefully handle all this cases.
- Added unary expressions (almost finished)
- Corrects referencing fields of objects.
- Call static objects and methods
- Improvesdistinction when referencing fields or local variables
- Corrects auto return functionality to be more natural
- Adds validation that the object being returned is the same as the method signature.
- POPs expressions without assignment from a block to keep clean the stack
- Add optional ";"
- Allow assignment of fields of other objects:

``` java
 foo.bar = 3
```
- Moves many language rules from the byte code generators to the parser to keep the rules more "vm" agnostic.

It is quite a big change but if interested I can create a pull request to join it with the main project. I plan to continue adding other changes to keep learning but I think this is something basic to have the bases of a language.

Let me know if there is interest.

**Comment by JakubDziworski** [comment]
Thanks a lot for an interest! I really appreciate it. The language is of course just a prototype and has a lot room for improvement, but some of the stuff you mentioned was "by design" - no statics, no fields assignment etc. However I'd gladly integrate other things  into this repo. I'd love to chat with you about this on gitter. Can you join?
